spring:
  application:
    name: config-server
server:
  port: 8080
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: metrics, health
      base-path: /management
